[
  "SPOS",
  "pilot",
  "DELIVERY",
  "PICKUP",
  "TaxExempt",
  "discount-engine",
  "InventoryOverride",
  "ChangePalletCount",
  "ChangeTruckType",
  "DeliveryChargeMarkdown",
  "NewDeliveryUI"
]
